language: node_js
node_js:
  - "8"
  - "6"
jobs:
  include:
    - stage: test
      name: 'Linting'
      script: npm run lint
    - name: 'Coverage'
      script: npm run coverage && npm run coveralls
    - name: 'E2E on Node.js 4'
      script: npm run e2e
      node_js: "4"
    - stage: release
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
