language: node_js
node_js:
    - "10"
    - "8"
jobs:
  include:
    - stage: test
      name: 'Linting'
      script:
        - npm run lint
        - commitlint-travis
    - name: 'Coverage'
      script: npm run coverage-coveralls
    - name: 'Build'
      script:
        - npm run build
        - npm run build-docs
    - stage: release
      name: 'Publish'
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
    - name: 'Document'
      if: branch = master
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: docs/public
