language: node_js
node_js: "lts/*"
jobs:
  include:
    - stage: test
      name: 'Linting'
      script: npm run lint
    - name: 'Coverage'
      script: npm run coverage-coveralls
    - stage: release
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
