language: node_js
node_js:
  - "8"
  - "6"
  - "4"
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: coverage
      script: npm run coverage && npm run coveralls
    - stage: release
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
