language: node_js
node_js: "8"
jobs:
  include:
    - stage: test
      name: 'Linting'
      script: npm run lint
    - name: 'Unit Test'
      script: npm run unit && npm run coveralls
    - name: 'E2E Test'
      script: npm run e2e
      node_js:
        - "8"
        - "6"
        - "4"

    - stage: build
      script: npm run build

    - stage: release
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
