language: node_js
node_js:
  - "8"
  - "6"
  - "4"
jobs:
  include:
    - stage: test
    - name: 'Linting'
      script: npm run lint
    - name: 'Unit Test'
      script: if (( $TRAVIS_NODE_VERSION >= 6 )); then npm run unit; fi
    - name: 'E2E Test'
      script: npm run e2e
    - name: 'Test Coverage'
      script: if (( $TRAVIS_NODE_VERSION >= 6 )); then npm run coveralls; fi

    - stage: build
      script: npm run build

    - stage: release
      if: branch = master
      node_js: "8"
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
